---
# tasks file for quorum configure 
- name: download necessary configs  
  git:
    repo: https://lesha-pharos@bitbucket.org/pharosproduction/quorum-single-node-config.git
    dest: /home/ops/configs
    force: yes
    