---
# tasks file for quorum setup

- name: Install packages
  apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
        - build-essential
        - git
        - libdb-dev
        - libleveldb-dev
        - libsodium-dev
        - zlib1g-dev
        - libtinfo-dev
        - sysvbanner
        - wget
        - dnsutils

- name: Download constellation
  get_url:
    url: https://github.com/jpmorganchase/constellation/releases/download/v0.3.5-build.1/constellation-0.3.5-ubuntu1604.tar.gz
    dest: /home/ops/constellation-0.3.5-ubuntu1604.tar.xz
    owner: ops
    group: ops
    mode: 0755

- name: Unpack constellation
  shell: cd /home/ops && tar xvf constellation-0.3.5-ubuntu1604.tar.xz && cp constellation-node /usr/local/bin


- name: Set permission to constellation
  file:
    path: /usr/local/bin/constellation-node
    owner: ops
    group: ops
    mode: 0755

- name: Clean folder after files downloads
  file:
    path: "{{ item }}"
    state: absent
  with_items:
   - /home/ops/constellation-0.3.5-ubuntu1604.tar.xz
   - /home/ops/constellation-node
- name: Download GO
  get_url:
    url: https://storage.googleapis.com/golang/{{ GOREL }}
    dest: /home/ops/{{ GOREL }}
    owner: ops
    group: ops
    mode: 0755

## Uncoment after playbook complete    
- name: Unpack go
  shell: cd /home/ops && tar xvf {{GOREL}} && mv go /usr/local/go

- name: set Go to PATH
  shell: export PATH=$PATH:/usr/local/go/bin

- name: set Go PATH to lesha .profile
  lineinfile:
    path: /home/ops/.profile
    regexp: '^#export GOPATH '
    line: export PATH=$PATH:/usr/local/go/bin

- name: set Go PATH to root .profile
  lineinfile:
    path: /root/.profile
    regexp: '^#export GOPATH '
    line: export PATH=$PATH:/usr/local/go/bin

- name: source .profile
  shell: source /home/ops/.profile | bash

- name: Clean folder after go downloads
  file:
    path: /home/ops/{{GOREL}} 
    state: absent

- name: Copy quorum files
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: ops
    group: ops
    mode: u=rwx,g=rwx,o=rx
  with_items:
    - geth
    - bootnode

- name: add ethereum ppa
  apt_repository:
    repo: ppa:ethereum/ethereum

- name: install packages for ethereum
  apt:      
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - software-properties-common #=0.96.20.7 
    - libdb-dev #=1:5.3.21~exp1ubuntu2
    - libleveldb-dev #=1.18-5
    - libsodium-dev #=1.0.8-5
    - zlib1g-dev #=1:1.2.8.dfsg-2ubuntu4.1
    - libtinfo-dev #=6.0+20160213-1ubuntu1
    - netbase #=5.3
    - ca-certificates #=20170717~16.04.1 
    - curl #=7.47.0-1ubuntu2.8 
    - solc #=1:0.4.24-0ubuntu1~xenial
    - dnsutils #=1:9.10.3.dfsg.P4-8ubuntu1.10

- name: install supervisor
  apt: 
    name: supervisor
    state: present
    update_cache: yes